/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Price = IDL.Record({
  'currency' : IDL.Text,
  'change' : IDL.Float64,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
});
export const Holding = IDL.Record({
  'currentPrice' : Price,
  'ticker' : IDL.Text,
  'shares' : IDL.Float64,
  'color' : IDL.Text,
  'avgCost' : IDL.Float64,
  'assetType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Portfolio = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Nat64,
  'holdings' : IDL.Vec(Holding),
  'lastUpdated' : IDL.Nat64,
  'isPublic' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCryptoHolding' : IDL.Func([Holding], [], []),
  'addHolding' : IDL.Func([IDL.Text, Holding], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePortfolioPrivacy' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'createPortfolio' : IDL.Func([IDL.Text], [], []),
  'deletePortfolio' : IDL.Func([IDL.Text], [], []),
  'fetchHistoricalData' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'fetchYahooData' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCryptoHistoricalData' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCryptoHoldings' : IDL.Func([], [IDL.Vec(Holding)], []),
  'getCryptoLivePrice' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getDefaultCurrency' : IDL.Func([], [IDL.Text], []),
  'getPortfolioPerformance' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], []),
  'getPublicPortfolio' : IDL.Func([IDL.Principal, IDL.Text], [Portfolio], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCryptoHolding' : IDL.Func([IDL.Text], [], []),
  'removeHolding' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCryptoTickers' : IDL.Func([IDL.Text], [IDL.Text], []),
  'searchTickers' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePortfolio' : IDL.Func([Portfolio], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Price = IDL.Record({
    'currency' : IDL.Text,
    'change' : IDL.Float64,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
  });
  const Holding = IDL.Record({
    'currentPrice' : Price,
    'ticker' : IDL.Text,
    'shares' : IDL.Float64,
    'color' : IDL.Text,
    'avgCost' : IDL.Float64,
    'assetType' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Portfolio = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Nat64,
    'holdings' : IDL.Vec(Holding),
    'lastUpdated' : IDL.Nat64,
    'isPublic' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCryptoHolding' : IDL.Func([Holding], [], []),
    'addHolding' : IDL.Func([IDL.Text, Holding], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePortfolioPrivacy' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'createPortfolio' : IDL.Func([IDL.Text], [], []),
    'deletePortfolio' : IDL.Func([IDL.Text], [], []),
    'fetchHistoricalData' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'fetchYahooData' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCryptoHistoricalData' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCryptoHoldings' : IDL.Func([], [IDL.Vec(Holding)], []),
    'getCryptoLivePrice' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getDefaultCurrency' : IDL.Func([], [IDL.Text], []),
    'getPortfolioPerformance' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getPortfolios' : IDL.Func([], [IDL.Vec(Portfolio)], []),
    'getPublicPortfolio' : IDL.Func([IDL.Principal, IDL.Text], [Portfolio], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCryptoHolding' : IDL.Func([IDL.Text], [], []),
    'removeHolding' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCryptoTickers' : IDL.Func([IDL.Text], [IDL.Text], []),
    'searchTickers' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePortfolio' : IDL.Func([Portfolio], [], []),
  });
};

export const init = ({ IDL }) => { return []; };